name       : sdcv
version    : 0.5.1
release    : 1
source     :
    - https://github.com/Dushistov/sdcv/archive/v0.5.1.tar.gz : d0c64429547adb127d5ff9f0f0db8c4bc663bc413dfb5b5d32c924a67171c247
license    : GPL-2.0
component  : office
summary    : sdcv - console version of StarDict
description: |
    sdcv is simple, cross-platform text-base utility for work with
    dictionaries in StarDict's format. The word from "list of words" may be
    string with leading '/' for using Fuzzy search algorithm, with leading 
    '|' for using full-text search, string may contain '?' and '*' for using
    regexp search. It work in interactive and not interactive mode. 
setup      : |
    %cmake .
build      : |
    %make
    %make lang
install    : |
    %make_install
