name       : sdcv
version    : 0.5.2
release    : 3
source     :
    - https://github.com/Dushistov/sdcv/archive/v0.5.2.tar.gz : ec08dc084a0748d5a89df01a20bbf294f09b0366295cd418000f15d2e043c4f7
license    : GPL-2.0-or-later
component  : office
summary    : sdcv - console version of StarDict
description: |
    sdcv is simple, cross-platform text-base utility for work with dictionaries in StarDict's format. The word from "list of words" may be string with leading '/' for using Fuzzy search algorithm, with leading '|' for using full-text search, string may contain '?' and '*' for using regexp search. It work in interactive and not interactive mode.
setup      : |
    %cmake .
build      : |
    %make
    %make lang
install    : |
    %make_install
